replicaCount: 1

image:
  repository: ghcr.io/nataliarrod-unisabana/k8s-microservice
  tag: "1.0.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  appEnv: "default"
  appVersion: "1.0.0"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi